// Generated by Selenium IDE
import { Builder, By, Key, logging, WebDriver } from 'selenium-webdriver'

import { config } from 'dotenv'
import { join } from 'path'
import { Options } from 'selenium-webdriver/chrome.js'
import { readFileSync, writeFileSync } from 'fs'
import axios from 'axios'
import { getPayload } from './getPayload'

const { Type } = logging

console.log(Type)
config({
	path: join(__dirname, '..', '.env'),
})

let runs = 0
const dashboardURL = 'https://people.zoho.in/peppercontentglobal/zp#home/dashboard'

const executionStatus = process.env.EXECUTION_STATUS ?? ''

const handleLogs = (entries: logging.Entry[]) => {
	entries = entries.sort((a, b) => a.timestamp - b.timestamp)
	for (let index = 0; index < entries.length; index++) {
		const entry = entries[index]
		console.log(entry)
	}
}

const sleep = async (timeout = 3000) => {
	return await new Promise((resolve) => setTimeout(resolve, timeout))
}
const isDebug = process.env.NODE_ENV === 'development'

const executionString = executionStatus === 'check-in' ? 'Check-In' : 'Check-Out'
const run = async (): Promise<void> => {
	const options = new Options()

	const cookies: { accounts: any[]; people: any[] } = JSON.parse(
		readFileSync(join(__dirname, '..', 'cookies.json')).toString()
	)

	if (!isDebug) {
		options.addArguments('--headless')
	}

	;['--incognito', '--js-flags=--expose-gc'].forEach(function (v) {
		options.addArguments(v)
	})
	options.setLoggingPrefs({ performance: 'ALL', browser: 'ALL', client: 'ALL' })

	options.setUserPreferences({
		'profile.default_content_setting_values.geolocation': 2,
	})

	const driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build()
	try {
		await addCookies(cookies, driver)
		await driver.get(dashboardURL)
		const current_url = await driver.getCurrentUrl()

		if (current_url !== dashboardURL) {
			if (!isDebug || process.env.ALLOW_LOGIN_IN_DEBUG === 'true') {
				await handleLogin(driver)
			}
			await driver.get(dashboardURL)
		}
		await sleep(1000)
		const status_tag = await driver.findElement(By.id('ZPD_Top_Att_Stat'))
		const current_status = await status_tag.getText()
		await sleep(1000)
		console.log(current_status, status_tag)
		if (current_status.toLowerCase() === executionStatus.toLowerCase()) {
			console.log('executing:', executionStatus)
			await status_tag.click()
		} else {
			runs += 1

			console.log('Failed to do:', executionStatus)
			console.log('Current status:', current_status)
			throw new Error('Failed to do: ' + executionStatus)
		}

		runs += 1

		await sleep(2_000)

		if (!isDebug) await driver.close()
		if (process.env.SLACK_HOOK) {
			await axios.post(process.env.SLACK_HOOK, {
				...getPayload(
					`${executionString} successful at ${new Date().toLocaleString('en-US', {
						timeZone: 'Asia/Kolkata',
					})}`,
					true
				),
			})
		}
	} catch (err) {
		console.error(err)
		await printLogs(driver)

		await driver.close()
		await driver.quit()
		if (runs === 0) {
			runs += 1
			return run()
		}
		try {
			if (process.env.SLACK_HOOK) {
				await axios.post(process.env.SLACK_HOOK, {
					...getPayload(
						`${executionString} failed at ${new Date().toLocaleString('en-US', {
							timeZone: 'Asia/Kolkata',
						})}`,
						false
					),
				})
			}
		} catch (err) {
			console.error(err)
		}
		throw new Error('Failed to execute script check-in')
	}
}

run()
	.then(() => {
		console.log('Success!')
		process.exit(0)
	})
	.catch((err) => {
		console.log(err)
		process.exit(1)
	})

async function addCookies(cookies: { accounts: any[]; people: any[] }, driver: WebDriver) {
	// for accounts
	await driver.get('https://accounts.zoho.in/')
	await driver.manage().window().setRect({ width: 1440, height: 900 })

	await addCookie(cookies.accounts, driver)

	// for people
	await driver.get('https://people.zoho.in/')
	await addCookie(cookies.people, driver)
}

async function addCookie(cookies: any[], driver: WebDriver) {
	for (let index = 0; index < cookies.length; index++) {
		const cookie = cookies[index]
		await driver.manage().addCookie(cookie)
	}
}

async function handleLogin(driver: WebDriver) {
	await driver.get('https://accounts.zoho.in/signin')

	await driver.findElement(By.id('login_id')).sendKeys(process.env.ZOHO_EMAIL!)

	await driver.findElement(By.id('login_id')).sendKeys(Key.ENTER)
	await sleep(1000)

	await driver.findElement(By.id('password')).sendKeys(process.env.ZOHO_PASSWORD!)

	await driver.findElement(By.id('password')).sendKeys(Key.ENTER)

	// wait until url changes for selenium
	await sleep(4_000)

	await driver.get('https://accounts.zoho.in/')

	const accounts = await driver.manage().getCookies()
	console.log('accounts', accounts)

	await driver.get(dashboardURL)
	const people = await driver.manage().getCookies()
	console.log('people', people)

	const cookies = { accounts, people }
	writeFileSync(join(__dirname, '..', 'cookies.json'), JSON.stringify(cookies, undefined, 4))
}

async function printLogs(driver: WebDriver) {
	await sleep(1000)
	const browserLogs = await driver.manage().logs().get('browser')
	const driverLogs = await driver.manage().logs().get('driver')
	const performanceLogs = await driver.manage().logs().get('performance')
	const logs: logging.Entry[] = [...browserLogs, ...driverLogs, ...performanceLogs]
	handleLogs(logs)
	return logs
}
